### ISSUE TITLE
panic: json: unsupported type: map[int]bool

### ISSUE THREAD

**Issue by neeraj-j** [mitroadmaps/roadtracer#8]
Hi,

While executing "go run 2_mkgraphs.go /data/planet.osm.pbf /data/rawgraphs/", I am encountering following error:

panic: json: unsupported type: map[int]bool

goroutine 1 [running]:
panic(0x7f6ec0, 0xc822928300)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.main.func1(0xc82000f120, 0x2, 0x2, 0xc82004db70, 0x7ffc0bfd807b, 0x12, 0xc820018180, 0x2, 0x2)
	roadtracer/dataset/2_mkgraphs.go:53 +0xd2
main.main()
	roadtracer/dataset/2_mkgraphs.go:58 +0xcc5
exit status 2

 Looking at the code :
			bytes, err := json.Marshal(motorwayEdges[i])
			if err != nil {
				panic(err)
			}

Its failing because json.Marshal takes only strings as key. while 
motorwayEdges := make([]map[int]bool, len(boundList)) ismade using int as keys. 

Am I missing something here. 
How to solve this issue.

**Comment by neeraj-j** [comment]
Add following code to resolve the issue
    
    mwE := make(map[string]bool)
    for key, value := range motorwayEdges[i] {
               mwE[strconv.Itoa(key)] = value  
    }

or upgrade golang-go to ver 1.10.1 on ubuntu.
